/**
 * Terms and Conditions, copied verbatim from the old site's terms (burnedout.xyz/terms-and-conditions,
 * which the old Disclaimer linked to as "terms of use"; it was generated by Complianz, last updated August 12, 2026).
 *
 * Only changes from the original:
 *  - links re-pointed to pages that exist on this site
 *  - section 26 ("Download", a PDF the Complianz plugin offered) removed
 *
 * ⚠️ Review with counsel before launch; see README. Section 9 is generic goods-return boilerplate
 * (14-day withdrawal, "goods", "delivery"), not a retreat refund policy.
 * Inline links use [text](/path).
 */
export type LegalBlock =
  | { type: "h2" | "h3" | "p"; text: string }
  | { type: "ul"; items: string[] };

export const termsUpdated = "August 12, 2026";

export const termsBlocks: LegalBlock[] = [
  {
    "type": "h2",
    "text": "1. Introduction"
  },
  {
    "type": "p",
    "text": "These Terms and conditions apply to this website and to the transactions related to our products and services. You may be bound by additional contracts related to your relationship with us or any products or services that you receive from us. If any provisions of the additional contracts conflict with any provisions of these Terms, the provisions of these additional contracts will control and prevail."
  },
  {
    "type": "h2",
    "text": "2. Binding"
  },
  {
    "type": "p",
    "text": "By registering with, accessing, or otherwise using this website, you hereby agree to be bound by these Terms and conditions set forth below. The mere use of this website implies the knowledge and acceptance of these Terms and conditions. In some particular cases, we can also ask you to explicitly agree."
  },
  {
    "type": "h2",
    "text": "3. Electronic communication"
  },
  {
    "type": "p",
    "text": "By using this website or communicating with us by electronic means, you agree and acknowledge that we may communicate with you electronically on our website or by sending an email to you, and you agree that all agreements, notices, disclosures, and other communications that we provide to you electronically satisfy any legal requirement, including but not limited to the requirement that such communications should be in writing."
  },
  {
    "type": "h2",
    "text": "4. Intellectual property"
  },
  {
    "type": "p",
    "text": "We or our licensors own and control all of the copyright and other intellectual property rights in the website and the data, information, and other resources displayed by or accessible within the website."
  },
  {
    "type": "h3",
    "text": "4.1 All the rights are reserved"
  },
  {
    "type": "p",
    "text": "Unless specific content dictates otherwise, you are not granted a license or any other right under Copyright, Trademark, Patent, or other Intellectual Property Rights. This means that you will not use, copy, reproduce, perform, display, distribute, embed into any electronic medium, alter, reverse engineer, decompile, transfer, download, transmit, monetize, sell, market, or commercialize any resources on this website in any form, without our prior written permission, except and only insofar as otherwise stipulated in regulations of mandatory law (such as the right to quote)."
  },
  {
    "type": "h2",
    "text": "5. Newsletter"
  },
  {
    "type": "p",
    "text": "Notwithstanding the foregoing, you may forward our newsletter in the electronic form to others who may be interested in visiting our website."
  },
  {
    "type": "h2",
    "text": "6. Third-party property"
  },
  {
    "type": "p",
    "text": "Our website may include hyperlinks or other references to other party’s websites. We do not monitor or review the content of other party’s websites which are linked to from this website. Products or services offered by other websites shall be subject to the applicable Terms and Conditions of those third parties. Opinions expressed or material appearing on those websites are not necessarily shared or endorsed by us."
  },
  {
    "type": "p",
    "text": "We will not be responsible for any privacy practices or content of these sites. You bear all risks associated with the use of these websites and any related third-party services. We will not accept any responsibility for any loss or damage in whatever manner, however caused, resulting from your disclosure to third parties of personal information."
  },
  {
    "type": "h2",
    "text": "7. Responsible use"
  },
  {
    "type": "p",
    "text": "By visiting our website, you agree to use it only for the purposes intended and as permitted by these Terms, any additional contracts with us, and applicable laws, regulations, and generally accepted online practices and industry guidelines. You must not use our website or services to use, publish or distribute any material which consists of (or is linked to) malicious computer software; use data collected from our website for any direct marketing activity, or conduct any systematic or automated data collection activities on or in relation to our website."
  },
  {
    "type": "p",
    "text": "Engaging in any activity that causes, or may cause, damage to the website or that interferes with the performance, availability, or accessibility of the website is strictly prohibited."
  },
  {
    "type": "h2",
    "text": "8. Registration"
  },
  {
    "type": "p",
    "text": "You may register for an account with our website. During this process, you may be required to choose a password. You are responsible for maintaining the confidentiality of passwords and account information and agree not to share your passwords, account information, or secured access to our website or services with any other person. You must not allow any other person to use your account to access the website because you are responsible for all activities that occur through the use of your passwords or accounts. You must notify us immediately if you become aware of any disclosure of your password."
  },
  {
    "type": "p",
    "text": "After account termination, you will not attempt to register a new account without our permission."
  },
  {
    "type": "h2",
    "text": "9. Refund and Return policy"
  },
  {
    "type": "h3",
    "text": "9.1 Right of withdrawal"
  },
  {
    "type": "p",
    "text": "You have the right to withdraw from this contract within 14 days without giving any reason."
  },
  {
    "type": "p",
    "text": "The withdrawal period will expire after 14 days from the day on which you acquire, or a third-party other than the carrier and indicated by you acquires, physical possession of the last good, or physical possession of the last lot or piece"
  },
  {
    "type": "p",
    "text": "To exercise your right of withdrawal, you must inform us of your decision to withdraw from this contract by an unequivocal statement. To this end, you may use the [withdrawal function available](/contact). You are, however, free to express your intention to withdraw from the contract by making an unequivocal statement in any other suitable way."
  },
  {
    "type": "p",
    "text": "You can also submit any other unequivocal statement on our [website](/contact)."
  },
  {
    "type": "p",
    "text": "We will communicate to you an acknowledgement of receipt of such a withdrawal on a durable medium (for example by email) without delay."
  },
  {
    "type": "p",
    "text": "To meet the withdrawal deadline, it is sufficient for you to send your communication concerning your exercise of the right of withdrawal before the withdrawal period has expired."
  },
  {
    "type": "h3",
    "text": "9.2 Effects of withdrawal"
  },
  {
    "type": "p",
    "text": "If you withdraw from this contract, we shall reimburse you all payments received from you, including the costs of delivery (with the exception of the supplementary costs resulting from your choice of a type of delivery other than the least expensive type of standard delivery offered by us), without undue delay and in any event not later than 14 days from the day on which we are informed about your decision to withdraw from this contract. We will carry out such reimbursement using the same means of payment as you used for the initial transaction unless you have expressly agreed otherwise; in any event, you will not incur any fees as a result of such reimbursement."
  },
  {
    "type": "p",
    "text": "You shall send back the goods or hand them over to us or a person authorised by us to receive the goods, without undue delay and in any event not later than 14 days from the day on which you communicate your withdrawal from this contract to us. The deadline is met if you send back the goods before the period of 14 days has expired."
  },
  {
    "type": "p",
    "text": "We may withhold reimbursement until we have received the goods back or you have supplied evidence of having sent back the goods, whichever is the earliest."
  },
  {
    "type": "p",
    "text": "We will bear the cost of returning / collecting the goods."
  },
  {
    "type": "p",
    "text": "You are only liable for any diminished value of the goods resulting from the handling other than what is necessary to establish the nature, characteristics, and functioning of the goods."
  },
  {
    "type": "p",
    "text": "Please note that there are some legal exceptions to the right to withdraw, and some items can therefore not be returned or exchanged. We will let you know if this applies in your particular case."
  },
  {
    "type": "h2",
    "text": "10. Idea submission"
  },
  {
    "type": "p",
    "text": "Do not submit any ideas, inventions, works of authorship, or other information that can be considered your own intellectual property that you would like to present to us unless we have first signed an agreement regarding the intellectual property or a non-disclosure agreement. If you disclose it to us absent such written agreement, you grant to us a worldwide, irrevocable, non-exclusive, royalty-free license to use, reproduce, store, adapt, publish, translate and distribute your content in any existing or future media."
  },
  {
    "type": "h2",
    "text": "11. Termination of use"
  },
  {
    "type": "p",
    "text": "We may, in our sole discretion, at any time modify or discontinue access to, temporarily or permanently, the website or any Service thereon. You agree that we will not be liable to you or any third party for any such modification, suspension or discontinuance of your access to, or use of, the website or any content that you may have shared on the website. You will not be entitled to any compensation or other payment, even if certain features, settings, and/or any Content you have contributed or have come to rely on, are permanently lost. You must not circumvent or bypass, or attempt to circumvent or bypass, any access restriction measures on our website."
  },
  {
    "type": "h2",
    "text": "12. Warranties and liability"
  },
  {
    "type": "p",
    "text": "Nothing in this section will limit or exclude any warranty implied by law that it would be unlawful to limit or to exclude. This website and all content on the website are provided on an “as is” and “as available” basis and may include inaccuracies or typographical errors. We expressly disclaim all warranties of any kind, whether express or implied, as to the availability, accuracy, or completeness of the Content. We make no warranty that:"
  },
  {
    "type": "ul",
    "items": [
      "this website or our products or services will meet your requirements;",
      "this website will be available on an uninterrupted, timely, secure, or error-free basis;",
      "the quality of any product or service purchased or obtained by you through this website will meet your expectations."
    ]
  },
  {
    "type": "p",
    "text": "Nothing on this website constitutes or is meant to constitute, legal, financial or medical advice of any kind. If you require advice you should consult an appropriate professional."
  },
  {
    "type": "p",
    "text": "The following provisions of this section will apply to the maximum extent permitted by applicable law and will not limit or exclude our liability in respect of any matter which it would be unlawful or illegal for us to limit or to exclude our liability. In no event will we be liable for any direct or indirect damages (including any damages for loss of profits or revenue, loss or corruption of data, software or database, or loss of or harm to property or data) incurred by you or any third party, arising from your access to, or use of, our website."
  },
  {
    "type": "p",
    "text": "Except to the extent any additional contract expressly states otherwise, our maximum liability to you for all damages arising out of or related to the website or any products and services marketed or sold through the website, regardless of the form of legal action that imposes liability (whether in contract, equity, negligence, intended conduct, tort or otherwise) will be limited to the actual amount the user paid in the 180 days prior. Such limit will apply in the aggregate to all of your claims, actions and causes of action of every kind and nature."
  },
  {
    "type": "h2",
    "text": "13. Privacy"
  },
  {
    "type": "p",
    "text": "To access our website and/or services, you may be required to provide certain information about yourself as part of the registration process. You agree that any information you provide will always be accurate, correct, and up to date."
  },
  {
    "type": "p",
    "text": "We take your personal data seriously and are committed to protecting your privacy. We will not use your email address for unsolicited mail. Any emails sent by us to you will only be in connection with the provision of agreed products or services."
  },
  {
    "type": "p",
    "text": "We have developed a policy to address any privacy concerns you may have. For more information, please see our [Privacy Statement](/privacy-statement-us) and our [Cookie Policy](/privacy-statement-us)."
  },
  {
    "type": "h2",
    "text": "14. Export restrictions / Legal compliance"
  },
  {
    "type": "p",
    "text": "Access to the website from territories or countries where the Content or purchase of the products or Services sold on the website is illegal is prohibited. You may not use this website in violation of export laws and regulations of United States."
  },
  {
    "type": "h2",
    "text": "15. Affiliate marketing"
  },
  {
    "type": "p",
    "text": "Through this Website we may engage in affiliate marketing whereby we receive a percentage of or a commission on the sale of services or products on or through this website. We may also accept sponsorships or other forms of advertising compensation from businesses. This disclosure is intended to comply with legal requirements on marketing and advertising which may apply, such as the US Federal Trade Commission Rules."
  },
  {
    "type": "h2",
    "text": "16. Assignment"
  },
  {
    "type": "p",
    "text": "You may not assign, transfer or sub-contract any of your rights and/or obligations under these Terms and conditions, in whole or in part, to any third party without our prior written consent. Any purported assignment in violation of this Section will be null and void."
  },
  {
    "type": "h2",
    "text": "17. Breaches of these Terms and conditions"
  },
  {
    "type": "p",
    "text": "Without prejudice to our other rights under these Terms and Conditions, if you breach these Terms and Conditions in any way, we may take such action as we deem appropriate to deal with the breach, including temporarily or permanently suspending your access to the website, contacting your internet service provider to request that they block your access to the website, and/or commence legal action against you."
  },
  {
    "type": "h2",
    "text": "18. Force majeure"
  },
  {
    "type": "p",
    "text": "Except for obligations to pay money hereunder, no delay, failure or omission by either party to carry out or observe any of its obligations hereunder will be deemed to be a breach of these Terms and conditions if and for as long as such delay, failure or omission arises from any cause beyond the reasonable control of that party."
  },
  {
    "type": "h2",
    "text": "19. Indemnification"
  },
  {
    "type": "p",
    "text": "You agree to indemnify, defend and hold us harmless, from and against any and all claims, liabilities, damages, losses and expenses, relating to your violation of these Terms and conditions, and applicable laws, including intellectual property rights and privacy rights. You will promptly reimburse us for our damages, losses, costs and expenses relating to or arising out of such claims."
  },
  {
    "type": "h2",
    "text": "20. Waiver"
  },
  {
    "type": "p",
    "text": "Failure to enforce any of the provisions set out in these Terms and Conditions and any Agreement, or failure to exercise any option to terminate, shall not be construed as waiver of such provisions and shall not affect the validity of these Terms and Conditions or of any Agreement or any part thereof, or the right thereafter to enforce each and every provision."
  },
  {
    "type": "h2",
    "text": "21. Language"
  },
  {
    "type": "p",
    "text": "These Terms and Conditions will be interpreted and construed exclusively in English. All notices and correspondence will be written exclusively in that language."
  },
  {
    "type": "h2",
    "text": "22. Entire agreement"
  },
  {
    "type": "p",
    "text": "These Terms and Conditions, together with our [privacy statement](/privacy-statement-us) and [cookie policy](/privacy-statement-us), constitute the entire agreement between you and BurnedOut Media LLC in relation to your use of this website."
  },
  {
    "type": "h2",
    "text": "23. Updating of these Terms and conditions"
  },
  {
    "type": "p",
    "text": "We may update these Terms and Conditions from time to time. The date provided at the beginning of these Terms and Conditions is the latest revision date. We will give you a written notice of any changes or updates, and the revised Terms and Conditions will become effective from the date that we give you such a notice. Your continued use of this website following the posting of changes or updates will be considered notice of your acceptance to abide by and be bound by these Terms and Conditions. To request a prior version of these Terms and conditions, please contact us."
  },
  {
    "type": "h2",
    "text": "24. Choice of Law and Jurisdiction"
  },
  {
    "type": "p",
    "text": "These Terms and Conditions shall be governed by the laws of United States. Any disputes relating to these Terms and Conditions shall be subject to the jurisdiction of the courts of United States. If any part or provision of these Terms and Conditions is found by a court or other authority to be invalid and/or unenforceable under applicable law, such part or provision will be modified, deleted and/or enforced to the maximum extent permissible so as to give effect to the intent of these Terms and Conditions. The other provisions will not be affected."
  },
  {
    "type": "h2",
    "text": "25. Contact information"
  },
  {
    "type": "p",
    "text": "This website is owned and operated by BurnedOut Media LLC."
  },
  {
    "type": "p",
    "text": "You may contact us regarding these Terms and Conditions through our [contact](/contact) page."
  }
];
